# DO NOT EDIT THIS FILE
# Put your customizations and configuration in hops_config.py

# Load all configuration (entries in Fabric's global `env` dict)
# from the hops_config module (either a hops_config.py file or
# hops_config/__init__.py on your PYTHONPATH)
from hops_config import *

# Load all hops commands
from hops.commands import *
